<?php
require_once 'PHPUnit/Framework.php';
require_once 'src/Wowheroes.php';

/**
 * Test class for WowPhpTools_Wowheroes.
 * Generated by PHPUnit on 2009-12-02 at 21:01:29.
 */
class WowPhpTools_WowheroesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var WowPhpTools_Wowheroes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WowPhpTools_Wowheroes;
    }

    /**
     * @dataProvider providerGetGuildRosterUrl
     */
    public function testGetGuildRosterUrl($realm, $guild, $expected) {
		$this->assertEquals(
			$this->object->getGuildRosterUrl($realm, $guild),
			$expected
		);
    }

	public function providerGetGuildRosterUrl() {
		return array(
			array('outland', 'mysth', 'http://xml.wow-heroes.com/xml-guild.php?z=eu&r=Outland&g=Mysth'),
			array('ravencrest', 'flying hellfish', 'http://xml.wow-heroes.com/xml-guild.php?z=eu&r=Ravencrest&g=Flying+Hellfish'),
			array('testRealm', 'Christiaan Baartse', 'http://xml.wow-heroes.com/xml-guild.php?z=eu&r=TestRealm&g=Christiaan+Baartse'),
		);
	}

    public function testGetGuild() {
		$xml = $this->object->getGuild('outland', 'mysth');
		$this->assertTrue($xml instanceof SimpleXMLElement);
		$this->assertTrue(isset($xml->guild->character));
    }
}
